name: Binary docker build

description: Build docker image for binary builds

inputs:
  docker-image-name:
    description: Docker image name for PR builds
    required: true
  docker-build-dir:
    description: Location of the build.sh relative to .ci/docker
    required: true
  custom-tag-prefix:
    description: Custom tag prefix for the docker image
    required: false
  DOCKER_TOKEN:
    description: Docker token for authentication
    required: true
  DOCKER_ID:
    description: Docker ID for authentication
    required: true

runs:
  using: composite
  steps:
    - name: Checkout PyTorch
      uses: pytorch/pytorch/.github/actions/checkout-pytorch@main

    - name: Calculate docker image
      uses: pytorch/test-infra/.github/actions/calculate-docker-image@csl/calculate_docker_image_custom_script_path
      with:
        docker-image-name: ${{ inputs.docker-image-name }}
        docker-build-dir: .ci/docker
        custom-tag-prefix: ${{ inputs.custom-tag-prefix }}
        docker-build-script: ${{ inputs.docker-build-dir }}/build.sh
        always-rebuild: true
        push: true

    - name: Authenticate if WITH_PUSH
      if: env.WITH_PUSH == 'true'
      env:
        DOCKER_TOKEN: ${{ inputs.DOCKER_TOKEN }}
        DOCKER_ID: ${{ inputs.DOCKER_ID }}
      shell: bash
      run: |
        if [[ "${WITH_PUSH}" == true ]]; then
          echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_ID}" --password-stdin
        fi

    - name: Build Docker Image
      if: env.WITH_PUSH == 'true'
      uses: nick-fields/retry@v3.0.0
      with:
        shell: bash
        timeout_minutes: 90
        max_attempts: 3
        retry_wait_seconds: 90
        command: |
          .ci/docker/${{ inputs.docker-build-dir }}/build.sh \
            ${{ inputs.docker-image-name }} \
            -t docker.io/${{ inputs.docker-image-name }}:${{ inputs.custom-tag-prefix }}-main
